# Site settings
title: Kevin & Anne
description: Um mural de um ano de namoro <3
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://ktakanomilk.github.io" # the base hostname & protocol for your site
author: Kevin Takano

# Collection settings
collections:
  photos:

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url:
instagram_url:
linkedin_url: 
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
